[package]
name = "k8s-pb-codegen"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "pbcodegen"
path = "pbcodegen.rs"

[dependencies]
bytes = "1.0.1"
prost = "0.8.0"
prost-build = "0.8.0"
prost-types = "0.8.0"
log = "0.4.14"
anyhow = "1.0.44"
env_logger = "0.9.0"
