[package]
name = "k8s-pb-codegen"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
publish = false

[dependencies]
bytes = "1.0.1"
prost = "0.12.3"
prost-build = "0.12.3"
prost-types = "0.12.3"
serde_json = "1.0.67"
serde = { version = "1.0.130", features = ["derive"] }
log = "0.4.14"
anyhow = "1.0.44"
env_logger = "0.10.1"
quote = "1.0"
heck = "0.3"
